sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/MessageHolderViewState.kt

This PR:
- Fixes the command line build for non-Linux users
- Updates documentation for building and signing a new release version
- Fixes sign up process by ensuring deletion of temporarily stored shared preferences.

FIX: Command line build + deletion of temporary shared preferences in onboard

---

sphinx/service/features/media-player/feature-service-media-player-android/src/main/AndroidManifest.xml
sphinx/service/features/media-player/feature-service-media-player-android/src/main/java/chat/sphinx/feature_service_media_player_android/service/MediaPlayerService.kt
sphinx/service/features/media-player/feature-service-media-player-android/src/main/java/chat/sphinx/feature_service_media_player_android/service/components/MediaPlayerNotification.kt

FIX: MediaPlayerService stops after Device entering Doze Mode

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt

Fix crash when app is sent to background

---

sphinx/application/common/resources/src/main/res/values/colors.xml
sphinx/screens-detail/camera/camera-utils/src/main/res/drawable/ic_shutter_focused.xml
sphinx/screens-detail/camera/camera-utils/src/main/res/drawable/ic_shutter_normal.xml
sphinx/screens-detail/camera/camera-utils/src/main/res/drawable/ic_shutter_pressed.xml
sphinx/screens-detail/camera/camera/src/main/java/chat/sphinx/camera/ui/CameraFragment.kt
sphinx/screens-detail/camera/camera/src/main/res/layout/fragment_camera.xml
sphinx/screens-detail/camera/camera/src/main/res/layout/layout_camera_footer.xml
sphinx/screens-detail/camera/camera/src/main/res/layout/layout_camera_image_preview.xml
sphinx/screens-detail/camera/camera/src/main/res/values/dimens.xml
sphinx/screens-detail/camera/camera/src/main/res/values/strings.xml
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/layout/fragment_payment_send.xml
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/values/dimens.xml
sphinx/screens-detail/send-attachment/send-attachment/src/main/java/chat/sphinx/send_attachment/ui/SendAttachmentViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_attachment_send_preview.xml
sphinx/screens/chats/chat-tribe/chat-tribe/src/main/res/layout/fragment_chat_tribe.xml

Layout adjustments for small devices

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt

update footer viewstate on successful retrieval of image from device

---

README.md
gradle/dependencies.gradle
local.defaults.properties
sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/GiphyData.kt
sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/Message.kt
sphinx/application/data/concepts/repositories/concept-repository-message/build.gradle
sphinx/application/data/concepts/repositories/concept-repository-message/src/main/java/chat/sphinx/concept_repository_message/model/SendMessage.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/screens/chats/chat-common/chat-common/build.gradle
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/SphinxEditText.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/attachment/AttachmentSendViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_chat_footer.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/strings.xml

Added Giphy Integration using the Giphy Android SDK and sending the giphy message in a similar fashion as it is sent in the ios app.
Also has some changes to read configs/API keys from local properties (with a `local.defaults.properties` so that the `BuildConfig` builds with some default values.

Giphy integration

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt

Most have slipped from my previous PRs

Fix chat view model build error

---

sphinx/application/common/wrappers/wrapper-common/build.gradle
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/lightning/Bolt11.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/lightning/LightningNodePubKey.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/lightning/LightningPaymentRequest.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/util/Bech32.kt
sphinx/application/common/wrappers/wrapper-common/src/test/java/chat/sphinx/wrapper_common/lightning/Bolt11Test.kt
sphinx/application/network/concepts/queries/concept-network-query-lightning/src/main/java/chat/sphinx/concept_network_query_lightning/NetworkQueryLightning.kt
sphinx/application/network/concepts/queries/concept-network-query-lightning/src/main/java/chat/sphinx/concept_network_query_lightning/model/invoice/PayRequestDto.kt
sphinx/application/network/concepts/queries/concept-network-query-lightning/src/main/java/chat/sphinx/concept_network_query_lightning/model/invoice/PaymentMessageDto.kt
sphinx/application/network/features/queries/feature-network-query-lightning/src/main/java/chat/sphinx/feature_network_query_lightning/NetworkQueryLightningImpl.kt
sphinx/application/network/features/queries/feature-network-query-lightning/src/main/java/chat/sphinx/feature_network_query_lightning/model/PayLightningPaymentRequestRelayResponse.kt
sphinx/screens-detail/payments/payment-send/payment-send/src/main/java/chat/sphinx/payment_send/ui/PaymentSendViewModel.kt
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/values/strings.xml
sphinx/screens-detail/qr-code/qr-code/src/main/java/chat/sphinx/qr_code/ui/QRCodeViewModel.kt
sphinx/screens/dashboard/dashboard/build.gradle
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardSideEffect.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt
sphinx/screens/dashboard/dashboard/src/main/res/values/strings.xml

https://github.com/stakwork/sphinx-kotlin/issues/220

Scanning invoices from Dashboard

---

sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt

Taking user to tribe chat instead of JoinTribe view if scanning tribe join link of tribe user is already in

Error joining tribe twice

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/adapters/MessageListAdapter.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/util/SphinxUrlSpan.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_holder_bubble.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_link_preview_contact.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_link_preview_tribe.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_link_preview_url.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/dimens.xml

- Fixes for long click menu showing on wrong place
- Loading wheeel and layout adjustments added on all link previews

Link Preview and Long Click fixes

---

sphinx/application/common/wrappers/wrapper-podcast/src/main/java/chat/sphinx/wrapper_podcast/PodcastDestination.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/application/network/concepts/queries/concept-network-query-chat/src/main/java/chat/sphinx/concept_network_query_chat/model/PodcastDestinationDto.kt
sphinx/application/network/concepts/queries/concept-network-query-chat/src/main/java/chat/sphinx/concept_network_query_chat/model/PostStreamSatsDestinationDto.kt
sphinx/screens-detail/podcast-player/podcast-player/src/main/java/chat/sphinx/podcast_player/objects/ParcelablePodcastDestination.kt

CustomKey and CustomValue added on podcast destinations (parsed from tribes server response and sent on streaming pmts request)

Podcast destination additions

---

sphinx/screens/profile/profile/src/main/java/chat/sphinx/profile/ui/ProfileViewModel.kt

Line breaks removed from backup keys exported string

---

sphinx/activity/main/activitymain/src/main/AndroidManifest.xml
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/MainActivity.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/MainViewModel.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/drivers/PrimaryNavigationDriver.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/navigation/ToDashboardScreen.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt
sphinx/screens/dashboard/dashboard/src/main/res/navigation/dashboard_nav_graph.xml

This PR depends on authorize-external PR and include the changes on that one. So authorize-external (#288) should be reviewed and merged first.

Deep links handling

---

sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/Message.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/adapters/MessageListAdapter.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_type_bot_response.xml

- Fixes to allow message menu on long click for bot response

Replying to bot response

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/adapters/MessageListAdapter.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/selected/MenuItemBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/selected/SelectedMessageViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_selected_message_menu.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/dimens.xml

- Fixes related with selected message view position for grouped messages
- Improvements related with menu position for small bubbles (related with flexible bubble width changes)

Message menu improvements

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/adapters/MessageListFooterAdapter.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_list_footer.xml

Bottom padding added on message list using FooterAdapter

Chat bottom padding

---

sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/Message.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/BubbleBackground.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/MessageHolderViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_holder.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_holder_bubble.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/dimens.xml

- Flexible bubble width for text messages

Flexible message bubble

---

sphinx/application/common/resources/src/main/java/chat/sphinx/resources/ContextExtensions.kt
sphinx/application/common/resources/src/main/res/drawable/ic_boost_grey.xml
sphinx/application/common/resources/src/main/res/layout/layout_chat_image_small_initial_holder.xml
sphinx/application/common/resources/src/main/res/values/dimens.xml
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/PhotoUrl.kt
sphinx/application/common/wrappers/wrapper-view/src/main/java/chat/sphinx/wrapper_view/Sp.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/adapters/MessageListAdapter.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/LayoutState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/MessageHolderViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_boost.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_boost_reaction_group.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/dimens.xml
sphinx/screens/chats/chat-contact/chat-contact/src/main/java/chat/sphinx/chat_contact/ui/ChatContactViewModel.kt
sphinx/screens/chats/chat-group/chat-group/src/main/java/chat/sphinx/chat_group/ui/ChatGroupViewModel.kt
sphinx/screens/chats/chat-tribe/chat-tribe/src/main/java/chat/sphinx/chat_tribe/ui/ChatTribeViewModel.kt

- Boost sender picture or initials showing on message reactions view
- Using thumbnail url for boost sender picture and received bubble sender picture
- Showing green icon if owner boosted message or message is sent
- Showing different amount font family and size depending on message direction (bigger font on sent messages)

Boost sender pictures

---

sphinx/screens-detail/video-screen/video-screen/src/main/java/chat/sphinx/video_screen/ui/watch/VideoFeedWatchScreenFragment.kt
sphinx/screens-detail/video-screen/video-screen/src/main/res/layout-land/layout_current_video_player.xml
sphinx/screens-detail/video-screen/video-screen/src/main/res/layout/layout_current_video_player.xml

Loading wheel added on video player to show while video is being prepared

Video player loading wheel

---

sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/navigators/detail/NewsletterDetailNavigatorImpl.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/navigators/primary/DashboardNavigatorImpl.kt
sphinx/application/data/concepts/concept-coredb/src/main/sqldelight/chat/sphinx/concept_coredb/SphinxDatabase.sq
sphinx/application/data/concepts/repositories/concept-repository-chat/src/main/java/chat/sphinx/concept_repository_chat/ChatRepository.kt
sphinx/application/data/concepts/repositories/concept-repository-media/src/main/java/chat/sphinx/concept_repository_media/RepositoryMedia.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/screens-detail/newsletter-detail/newsletter-detail/src/main/java/chat/sphinx/newsletter_detail/navigation/NewsletterDetailNavigator.kt
sphinx/screens-detail/newsletter-detail/newsletter-detail/src/main/java/chat/sphinx/newsletter_detail/ui/NewsletterDetailViewModel.kt
sphinx/screens-detail/video-screen/video-screen/src/main/java/chat/sphinx/video_screen/ui/watch/VideoFeedWatchScreenViewModel.kt
sphinx/screens-detail/web-view/web-view/build.gradle
sphinx/screens-detail/web-view/web-view/src/main/java/chat/sphinx/web_view/navigation/ToWebViewDetail.kt
sphinx/screens-detail/web-view/web-view/src/main/java/chat/sphinx/web_view/ui/WebViewViewModel.kt
sphinx/screens-detail/web-view/web-view/src/main/res/navigation/web_view_nav_graph.xml
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/navigation/DashboardNavigator.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/adapter/DashboardChat.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/feed/read/FeedReadViewModel.kt
sphinx/service/features/media-player/feature-service-media-player-android/src/main/java/chat/sphinx/feature_service_media_player_android/MediaPlayerServiceControllerImpl.kt
sphinx/service/features/media-player/feature-service-media-player-android/src/main/java/chat/sphinx/feature_service_media_player_android/service/MediaPlayerService.kt

- Updating content_seen_at when playing podcast, watching video or reading newsletter articles
- Using date to order chats on chat list

Content seen date logic

---

sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_message_holder.xml

Fix chat bubble angular edges

---

sphinx/application/common/resources/src/main/java/chat/sphinx/resources/ContextExtensions.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/adapter/ChatListAdapter.kt
sphinx/screens/dashboard/dashboard/src/main/res/layout/layout_chat_list_chat_holder.xml

- Fixes related with muted icon on chats list row
- Changes related with badge count text view on muted chats

Chats list layout fixes

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatSideEffect.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/selected/MenuItemState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/values-es/strings.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values-ja/strings.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values-zh/strings.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/dimens.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/strings.xml

- Order changed on message options menu
- Options height slightly increased
- Confirmation added for FLAG and DELETE options

Message options menu improvements

---

sphinx/application/common/resources/src/main/res/values/colors.xml
sphinx/application/common/resources/src/main/res/values/themes.xml
sphinx/screens-detail/chat-detail/tribe-detail/src/main/java/chat/sphinx/tribe_detail/ui/TribeDetailSideEffect.kt
sphinx/screens-detail/create-tribe/create-tribe/src/main/java/chat/sphinx/create_tribe/ui/CreateTribeSideEffect.kt
sphinx/screens-detail/payments/payment-common/payment-common/src/main/java/chat/sphinx/payment_common/ui/PaymentSideEffect.kt
sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionSideEffect.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatSideEffect.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/ChatListSideEffect.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardSideEffect.kt
sphinx/screens/onboard/onboard-message/src/main/java/chat/sphinx/onboard/ui/OnBoardMessageSideEffect.kt
sphinx/screens/profile/profile/src/main/java/chat/sphinx/profile/ui/ProfileSideEffect.kt

Custom styles for Alert Dialogs

---

gradle/dependencies.gradle
sphinx/screens/dashboard/dashboard/build.gradle
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/workers/BackgroundRefreshWorker.kt

Background fetch implemented to get new contacts and messages while in background

Background fetch

---

sphinx/screens/address-book/address-book/src/main/java/chat/sphinx/address_book/ui/AddressBookFragment.kt
sphinx/screens/address-book/address-book/src/main/java/chat/sphinx/address_book/ui/AddressBookSideEffect.kt
sphinx/screens/address-book/address-book/src/main/java/chat/sphinx/address_book/ui/AddressBookViewModel.kt
sphinx/screens/address-book/address-book/src/main/java/chat/sphinx/address_book/ui/adapter/AddressBookListAdapter.kt
sphinx/screens/address-book/address-book/src/main/res/values-es/strings.xml
sphinx/screens/address-book/address-book/src/main/res/values-ja/strings.xml
sphinx/screens/address-book/address-book/src/main/res/values-zh/strings.xml
sphinx/screens/address-book/address-book/src/main/res/values/strings.xml

Showing toast about swipe left when long clicking a contact on address book

Contact long click alert

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/selected/SelectedMessageViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_selected_message_menu.xml

Showing message menu over message instead of out of screen bounds

Message menu position fix

---

sphinx/application/data/concepts/repositories/concept-repository-dashboard/src/main/java/chat/sphinx/concept_repository_dashboard/RepositoryDashboard.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt

- Showing restore popup while restoring contacts

Restore improvements

---

sphinx/screens-detail/payments/payment-template/payment-template/src/main/java/chat/sphinx/payment_template/ui/PaymentTemplateViewModel.kt

Fix for multiple payments going out when tapping multiple times on CONFIRM button on payment templates view

Spam clicking send on chat pmts #431

---

sphinx/screens-detail/newsletter-detail/newsletter-detail/src/main/java/chat/sphinx/newsletter_detail/ui/adapter/NewsletterItemsListAdapter.kt
sphinx/screens/chats/chat-tribe/chat-tribe/src/main/java/chat/sphinx/chat_tribe/ui/ChatTribeFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt

Podcast placeholder set for podcast episodes images (was using profile placeholder before)

Podcast placeholder

---

sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardPodcastViewModel.kt

reappearing on dashboard when coming back from chat (not playing state)

Fix for podcast bar

---

sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/util/Extensions.kt

Fix for pricePerMessage and escrowAmount being reset on tribes when sending message

Tribe message price

---

gradle.properties

Gradle configuration to avoid native libs optimization

Google Play Tor fix

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt

Using real file name when saving to device storage

Downloaded file name

---

sphinx/screens-detail/payments/payment-receive/payment-receive/src/main/java/chat/sphinx/payment_receive/ui/PaymentReceiveViewModel.kt
sphinx/screens-detail/payments/payment-send/payment-send/src/main/java/chat/sphinx/payment_send/ui/PaymentSendViewModel.kt
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/values-es/strings.xml
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/values-ja/strings.xml
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/values-zh/strings.xml
sphinx/screens-detail/payments/payment-send/payment-send/src/main/res/values/strings.xml

Payments amount limit set to 7 digits

Payments amount limit

---

sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/navigators/primary/DashboardNavigatorImpl.kt
sphinx/application/common/resources/src/main/res/values-es/strings.xml
sphinx/application/common/resources/src/main/res/values-ja/strings.xml
sphinx/application/common/resources/src/main/res/values-zh/strings.xml
sphinx/application/common/resources/src/main/res/values/strings.xml
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/CreateInvoiceLink.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/StakworkAuthorizeLink.kt
sphinx/application/data/concepts/repositories/concept-repository-dashboard/src/main/java/chat/sphinx/concept_repository_dashboard/RepositoryDashboard.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/screens-detail/payments/payment-receive/payment-receive/src/main/java/chat/sphinx/payment_receive/ui/PaymentReceiveViewModel.kt
sphinx/screens-detail/payments/payment-receive/payment-receive/src/main/res/values-es/strings.xml
sphinx/screens-detail/payments/payment-receive/payment-receive/src/main/res/values-ja/strings.xml
sphinx/screens-detail/payments/payment-receive/payment-receive/src/main/res/values-zh/strings.xml
sphinx/screens-detail/payments/payment-receive/payment-receive/src/main/res/values/strings.xml
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/navigation/DashboardNavigator.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/viewstates/DeepLinkPopupViewState.kt

- Stakwork authorize popup and logic implemented
- Stakwork invoice logic implemented

Stakwork integration

---

sphinx/application/common/resources/src/main/res/values-es/strings.xml
sphinx/application/common/resources/src/main/res/values-ja/strings.xml
sphinx/application/common/resources/src/main/res/values-zh/strings.xml
sphinx/application/common/resources/src/main/res/values/strings.xml
sphinx/screens/profile/profile/src/main/java/chat/sphinx/profile/ui/ProfileFragment.kt
sphinx/screens/profile/profile/src/main/java/chat/sphinx/profile/ui/ProfileSideEffect.kt
sphinx/screens/profile/profile/src/main/java/chat/sphinx/profile/ui/ProfileViewModel.kt
sphinx/screens/profile/profile/src/main/java/chat/sphinx/profile/ui/ProfileViewState.kt
sphinx/screens/profile/profile/src/main/res/values-es/strings.xml
sphinx/screens/profile/profile/src/main/res/values-ja/strings.xml
sphinx/screens/profile/profile/src/main/res/values-zh/strings.xml
sphinx/screens/profile/profile/src/main/res/values/strings.xml

- Setup Device button label changed
- Checking network before starting process
- Other fixes and improvements

Signing Device setup

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/util/SphinxLinkify.kt

this closes https://github.com/stakwork/sphinx-kotlin/issues/482

Fix for issue #482. Route hint not populated

---

sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatSideEffect.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/values-es/strings.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values-ja/strings.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values-zh/strings.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/strings.xml

**This PR resolve this issue #496** 
i made some changes to be able to delete or block a contact directly from the chat before you have to go to Address Book to do so 
https://user-images.githubusercontent.com/92212925/192551573-db4454ac-baf6-4a40-a569-2be246b337ba.mp4

Enhancement -> user now able to Delete / Block contact directly from Chat

---

sphinx/screens-detail/scanner/scanner/src/main/java/chat/sphinx/scanner/ui/ScannerFragment.kt
sphinx/screens-detail/scanner/scanner/src/main/res/drawable/ic_gallary.xml
sphinx/screens-detail/scanner/scanner/src/main/res/layout/fragment_scanner.xml

@tomastiminskas 
**implemented new feature** 
users are now able to read QR codes by choosing image from their gallery  
https://user-images.githubusercontent.com/92212925/189506301-6c698cf5-2245-4880-a271-d41430c633c7.mp4

Feat: Read QR code from gallery 

---

sphinx/screens-detail/scanner/scanner/src/main/java/chat/sphinx/scanner/ui/ScannerFragment.kt
sphinx/screens-detail/scanner/scanner/src/main/res/layout/fragment_scanner.xml

- Fix for scanner crashing when dismissing gallery
- Some layout adjustments

Scanner gallery fixes

---

sphinx/application/data/concepts/repositories/concept-repository-actions/src/main/java/chat/sphinx/concept_repository_actions/ActionsRepository.kt
sphinx/screens-detail/podcast-player/podcast-player/src/main/java/chat/sphinx/podcast_player/ui/PodcastPlayerViewModel.kt
sphinx/screens-detail/video-screen/video-screen/src/main/java/chat/sphinx/video_screen/ui/watch/VideoRecordConsumed.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/feed/FeedViewModel.kt

Filtering feed searches

---

sphinx/application/common/wrappers/wrapper-common/build.gradle
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/message/CallLinkMessage.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/message/SphinxCallLink.kt
sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/Message.kt
sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/MessageContentDecrypted.kt
sphinx/application/common/wrappers/wrapper-message/src/main/java/chat/sphinx/wrapper_message/MessageType.kt
sphinx/application/data/concepts/concept-coredb/src/main/sqldelight/chat/sphinx/concept_coredb/SphinxDatabase.sq
sphinx/application/data/concepts/repositories/concept-repository-message/src/main/java/chat/sphinx/concept_repository_message/model/SendMessage.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/mappers/message/MessageDboPresenterMapper.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/model/message/MessageDboWrapper.kt
sphinx/application/network/concepts/queries/concept-network-query-message/src/main/java/chat/sphinx/concept_network_query_message/model/PostMessageDto.kt
sphinx/screens/chats/chat-common/chat-common/build.gradle
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/messageholder/HolderBindingExtensions.kt
sphinx/screens/chats/chat-contact/chat-contact/build.gradle
sphinx/screens/chats/chat-contact/chat-contact/src/main/java/chat/sphinx/chat_contact/ui/ChatContactViewModel.kt
sphinx/screens/chats/chat-group/chat-group/build.gradle
sphinx/screens/chats/chat-group/chat-group/src/main/java/chat/sphinx/chat_group/ui/ChatGroupViewModel.kt
sphinx/screens/chats/chat-tribe/chat-tribe/src/main/java/chat/sphinx/chat_tribe/ui/ChatTribeViewModel.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/adapter/DashboardChat.kt

- Handling UI
- Sending new type when on 1:1 conversation

New call message type implemented

---

sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragmentsAdapter.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt

Selector bug between tables after navigating in a Tribe is been solved.

Fix selector from tribes to friends

---

sphinx/application/common/resources/src/main/res/layout/layout_feed_item.xml
sphinx/screens-detail/video-screen/video-screen/src/main/java/chat/sphinx/video_screen/ui/watch/VideoFeedWatchScreenFragment.kt

Fix for feed item view not working on recommendations and podcast player

Feed Item View

---

sphinx/screens-detail/delete-chat-media-detail/delete-chat-media-detail/src/main/java/chat/sphinx/example/delete_chat_media_detail/ui/DeleteChatMediaDetailFragment.kt
sphinx/screens-detail/delete-chat-media-detail/delete-chat-media-detail/src/main/java/chat/sphinx/example/delete_chat_media_detail/ui/DeleteChatMediaDetailViewModel.kt
sphinx/screens-detail/delete-chat-media-detail/delete-chat-media-detail/src/main/java/chat/sphinx/example/delete_chat_media_detail/viewstate/DeleteChatDetailNotificationViewState.kt
sphinx/screens-detail/delete-chat-media/delete-chat-media/src/main/java/chat/sphinx/delete_chat_media/ui/DeleteChatMediaFragment.kt
sphinx/screens-detail/delete-chat-media/delete-chat-media/src/main/java/chat/sphinx/delete_chat_media/ui/DeleteChatMediaViewModel.kt
sphinx/screens-detail/delete-chat-media/delete-chat-media/src/main/java/chat/sphinx/delete_chat_media/viewstate/DeleteChatNotificationViewState.kt
sphinx/screens-detail/delete-podcast-detail/delete-podcast-detail/src/main/java/chat/sphinx/example/delete_media_detail/ui/DeletePodcastDetailFragment.kt
sphinx/screens-detail/delete-podcast-detail/delete-podcast-detail/src/main/java/chat/sphinx/example/delete_media_detail/ui/DeletePodcastDetailViewModel.kt
sphinx/screens-detail/delete-podcast-detail/delete-podcast-detail/src/main/java/chat/sphinx/example/delete_media_detail/viewstate/DeleteAllNotificationViewStateContainer.kt
sphinx/screens-detail/delete-podcast-detail/delete-podcast-detail/src/main/java/chat/sphinx/example/delete_media_detail/viewstate/DeleteItemNotificationViewState.kt
sphinx/screens-detail/delete-podcast/delete-podcast/src/main/java/chat/sphinx/example/delete_media/ui/DeletePodcastFragment.kt
sphinx/screens-detail/delete-podcast/delete-podcast/src/main/java/chat/sphinx/example/delete_media/ui/DeletePodcastViewModel.kt
sphinx/screens-detail/delete-podcast/delete-podcast/src/main/java/chat/sphinx/example/delete_media/viewstate/DeleteNotificationViewState.kt
sphinx/screens-detail/manage-storage/manage-storage/src/main/java/chat/sphinx/example/manage_storage/ui/ManageStorageViewModel.kt

- Use MutableStateFlow on delete modules

---

sphinx/application/common/resources/src/main/res/drawable/background_scroll_down_button.xml
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/adapters/MessageListAdapter.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatViewModel.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/viewstate/scrolldown/ScrollDownViewState.kt
sphinx/screens/chats/chat-common/chat-common/src/main/res/layout/layout_scroll_down_button.xml
sphinx/screens/chats/chat-common/chat-common/src/main/res/values/dimens.xml
sphinx/screens/chats/chat-contact/chat-contact/src/main/java/chat/sphinx/chat_contact/ui/ChatContactFragment.kt
sphinx/screens/chats/chat-contact/chat-contact/src/main/res/layout/fragment_chat_contact.xml
sphinx/screens/chats/chat-group/chat-group/src/main/java/chat/sphinx/chat_group/ui/ChatGroupFragment.kt
sphinx/screens/chats/chat-group/chat-group/src/main/res/layout/fragment_chat_group.xml
sphinx/screens/chats/chat-tribe/chat-tribe/src/main/java/chat/sphinx/chat_tribe/ui/ChatTribeFragment.kt
sphinx/screens/chats/chat-tribe/chat-tribe/src/main/res/layout/fragment_chat_tribe.xml

Show scroll down button when the chat message adapter is not in on the last message.

Implement scroll down button on chat

---

sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt

Check if rsaPublicKey is not null before sending message to the peopl…

Connect to people fix

---

sphinx/screens-detail/web-view/web-view/src/main/java/chat/sphinx/web_view/ui/WebViewFragment.kt

- Default browser is open if url contains open=system

Open default browser when click for certain urls on WebViewFragment

---

sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/MainActivity.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/MainViewModel.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/drivers/AuthenticationNavigationDriver.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/drivers/DetailNavigationDriver.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/navigation/drivers/PrimaryNavigationDriver.kt
sphinx/activity/main/activitymain/src/main/java/chat/sphinx/activitymain/ui/MainViewState.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/chat/PushNotificationLink.kt
sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardFragment.kt
sphinx/screens/dashboard/dashboard/src/main/java/chat/sphinx/dashboard/ui/DashboardViewModel.kt
sphinx/service/features/notifications/feature-service-notification-firebase/build.gradle
sphinx/service/features/notifications/feature-service-notification-firebase/src/main/java/chat/sphinx/feature_service_notification_firebase/SphinxFirebaseMessagingService.kt

- Tap on push not taking user to specific chat
- Tap on push not opening app when force closed

Handling push notification to fix issues:

---

sphinx/application/data/concepts/concept-coredb/src/main/sqldelight/chat/sphinx/concept_coredb/SphinxDatabase.sq
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt

- Update rust library to v0.4.7
- set threadUuid

Implement reply messages

---

sphinx/application/common/resources/src/main/java/chat/sphinx/resources/sphinxrs.kt
sphinx/application/common/wrappers/wrapper-common/src/main/java/chat/sphinx/wrapper_common/lightning/Bolt11.kt
sphinx/application/data/concepts/repositories/concept-repository-message/src/main/java/chat/sphinx/concept_repository_message/MessageRepository.kt
sphinx/application/data/features/feature-connect-manager/src/main/java/chat/sphinx/feature_connect_manager/ConnectManagerImpl.kt
sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
sphinx/screens-detail/chat-detail/tribe-detail/src/main/java/chat/sphinx/tribe_detail/ui/TribeDetailViewModel.kt
sphinx/screens-detail/create-tribe/create-tribe/src/main/java/chat/sphinx/create_tribe/ui/CreateTribeViewModel.kt
sphinx/screens-detail/tribe-members-list/tribe-members-list/src/main/java/chat/sphinx/tribe_members_list/ui/TribeMembersListViewModel.kt
sphinx/screens-detail/tribes-discover/tribes-discover/src/main/java/chat/sphinx/tribes_discover/ui/TribesDiscoverViewModel.kt

- Fix tribe member list 
- Fix message type on invoices

Implement delete tribe
